# standard jekyll configuration

permalink: /posts/:title.html
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# custom options
google_analytics:
  account: UA-XXXXX-X

disqus:
  enable: true
  id: oguzbilgic
